[project]
name = "cognee-community-vector-adapter-azure"
version = "1.0.0"
description = "Azure AI search vector database adapter for cognee"
readme = "README.md"
requires-python = "<=3.13,>=3.10"
dependencies = [
    "azure-search-documents>=11.4.0",
    "azure-core>=1.29.0",
    "cognee>=0.1.41"
]

[project.urls]
Homepage = "https://www.cognee.ai"
Repository = "https://github.com/topoteretes/cognee-community"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/.venv",
]
