[project]
name = "cognee-community-vector-adapter-redis"
version = "0.0.1"
description = "Redis vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "redisvl>=0.6.0,<=1.0.0",
    "cognee>=0.2.0.dev0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/.venv",
]